services:
  mysql:
    image: mysql:8.4
    container_name: company_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company_db
      MYSQL_USER: cuong_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - company_mysql_data:/var/lib/mysql

volumes:
  company_mysql_data: